# Header
nav:
#  posts:
#    path: ./archives
#    icon: mingcute:inbox-fill
#    show_text: true
#  about:
#    path: ./about
#    icon: mingcute:user-info-fill
#    show_text: true
#  categories:
#    path: ./categories
#    icon: mingcute:classify-2-fill
#    show_icon: true
#  tags:
#    path: ./tags
#    icon: mingcute:tag-fill
#    show_icon: true
#  home:
#    path: ./index
#    icon: mingcute:home-2-fill
#    show_icon: true

#email: "evan.wangjue@gmail.com"
#my_location: Hangzhou, China
show_features_posts: false
year_align_center: false

# favicon
favicon: /images/favicon-32x32.png

# Portrait
portrait: https://file-proxy.deno.dev/https://avatars.githubusercontent.com/u/15522856?v=4
show_profile_image: true

# logo
logo: /images/logo.svg

# links
links:
  Github:
    link: https://www.github.com/sydeevans
    icon: mingcute:github-fill
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping: